# Generated by Django 5.1.2 on 2024-11-02 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la membresía",
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Semanal"),
                            ("biweekly", "Quincenal"),
                            ("monthly", "Mensual"),
                            ("semiannual", "Semestral"),
                            ("annual", "Anual"),
                            ("custom", "Custom"),
                            ("single_visit", "Visita única"),
                        ],
                        default="custom",
                        help_text="Tipo de membresía",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        help_text="Duración de la membresía (solo en membresías personalizadas.",
                        verbose_name="Duración",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio de la membresía",
                        max_digits=8,
                        verbose_name="Precio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membresía",
                "verbose_name_plural": "Membresías",
            },
        ),
        migrations.CreateModel(
            name="MembershipSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Start date of the subscription",
                        verbose_name="Fecha de inicio de la suscripción",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="End date of the subscription",
                        verbose_name="Fecha de finalización de la suscripción",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="customers.client",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="memberships.membership",
                        verbose_name="Membresía",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción",
                "verbose_name_plural": "Suscripciones",
            },
        ),
    ]
